# Usage:
#   docker compose up --build --detach
#   docker compose logs --tail 100 --follow

x-common-args: &x-common-args
  MC_VERSION: 1.18-rc4
  VT_VERSION: 1.17
  VT_DATAPACKS: '
    {
      "survival": [
        "fast leaf decay",
        "afk display",
        "multiplayer sleep",
        "graves",
        "durability ping",
        "track raw statistics",
        "villager workstation highlights"
      ],
      "items": [
        "armored elytra",
        "player head drops"
      ],
      "mobs": [
        "dragon drops",
        "more mob heads",
        "silence mobs",
        "villager death messages"
      ],
      "hermitcraft": [
        "wandering trades"
      ]
    }'
  VT_CRAFTING: '
    {
      "quality of life": [
        "dropper to dispenser",
        "rotten flesh to leather",
        "universal dyeing"
      ]
    }'
  LEGACY_ADVANCEMENTS: 'true'

x-rcon-env: &x-rcon-env
  ENABLE_RCON: 'true'
  RCON_PASSWORD: 1e39d9107c690b3b447d1896b11c8f6a


services:
  
  mc-server:
    build: 
      context: ./src
      args:
        <<: *x-common-args
        IMAGE: optimised-server
    restart: unless-stopped
    environment:
      <<: *x-rcon-env
      ACCEPT_EULA: 'true'
      SEED: Wollongang
    volumes:
      - minecraft:/app/minecraft
    ports:
      - 25565:25565

  world-backup:
    build: 
      context: ./src
      args:
        <<: *x-common-args
        IMAGE: world-backup
    restart: unless-stopped
    environment:
      <<: *x-rcon-env
    volumes:
      - minecraft:/app/minecraft
      - backups:/app/backups
    links:
      - mc-server


volumes:
  minecraft:
  backups:
