# Usage:
#   docker compose up --build --detach
#   docker compose logs --tail 100 --follow

x-common-args: &x-common-args
  MC_VERSION: 1.18-rc3

x-rcon-env: &x-rcon-env
  ENABLE_RCON: 'true'
  RCON_PASSWORD: 1e39d9107c690b3b447d1896b11c8f6a


services:
  
  mc-server:
    build: 
      context: ./src
      args:
        <<: *x-common-args
        IMAGE: optimised-server
    restart: unless-stopped
    environment:
      <<: *x-rcon-env
      ACCEPT_EULA: 'true'
      SEED: Wollongang
    volumes:
      - minecraft:/app/minecraft
    ports:
      - 25565:25565

  world-backup:
    build: 
      context: ./src
      args:
        <<: *x-common-args
        IMAGE: world-backup
    restart: unless-stopped
    environment:
      <<: *x-rcon-env
    volumes:
      - minecraft:/app/minecraft
      - backups:/app/backups
    links:
      - mc-server


volumes:
  minecraft:
  backups:
